### ISSUE TITLE
Unattended build

### ISSUE THREAD

**Issue by jfilak** [tobiashofmann/sap-nw-abap-docker#1]
Hi, in fact, it is possible to build the docker image without user interaction:
https://github.com/filak-sap/sap-nw-abap-docker

**Comment by tobiashofmann** [comment]
Hi @jfilak 

yes, it is possible. In the original version the script is created, but not run in the build process (run.sh is commented out). I did this because in a "normal" Docker env you must first adjust Docker for the large image size.

In case people want to create a volume for /sapmnt, the can do so and later run the unattended script. 

For the 7.52 SP01 version the new Dockerfile runs the installation automatically.
