### ISSUE TITLE
Errors while bulding: net-tools-deprecated not found & chown: invalid user: 'uuidd'

### ISSUE THREAD

**Issue by BlackmanCC** [tobiashofmann/sap-nw-abap-docker#13]
I am trying to build the docker file for nw 7.52 sp4 and get 2 errors:

1. The dockerfiles references opensuse/archive;latest. With the actual version tagged as latest (42.1) I get the error that the package "net-tools-deprectated" is not available
-> after changing to opensuse/archive:42.1 the error disappears an the package can be downloaded
2. chown: invalid user: 'uuidd'
The command '/bin/sh -c mkdir /run/uuidd && chown uuidd /var/run/uuidd && /usr/sbin/uuidd' returned a non-zero code: 1

**Comment by amo42** [comment]
I used the image some time ago, I think the used opensuse base image is missing the uuid deamon, therefore it fails during the startup. 

In case the docker container is still running, you can check from within the container if restarting the uuid deamon helps: `/etc/init.d/uuidd restart` or try to install it manually.

As far as I know, I used another image since the old ones are not maintained. Switching to another image solved all my issues, but I could not remember which one I used - sorry. Did you try some images from here: opensuse/leap ?

**As an update**, I've just tried it with the latest leap docker base image:
```
…
Step 6/16 : RUN mkdir /run/uuidd && chown uuidd /var/run/uuidd && /usr/sbin/uuidd
 ---> Running in bb6bf4050027
Removing intermediate container bb6bf4050027
 ---> db696b7279bf
Step 7/16 : COPY NW752 /var/tmp/NW752/
```
And it seams to work just fine. Since I did not have the files on my device, Step 7 failed

So this is my Dockerfile line 1:
`FROM opensuse/leap:latest`

Best
Andreas

**Comment by BlackmanCC** [comment]
Thanks for your help. It was easier and faster to build the docker image on my fast iMac adn after this I transfered it to the target machine.
btw: I used the opensuse/leap and everything works now.

Thanks for your fast reply.
Regards
Jens
